package tools

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// SnackFile represents a single file in an Expo Snack project.
type SnackFile struct {
	Type     string `json:"type"`     // "CODE" or "ASSET"
	Contents string `json:"contents"` // file text content
}

// SnackPushRequest is the payload sent to the Snack save API.
type SnackPushRequest struct {
	Name        string               `json:"name"`
	Description string               `json:"description"`
	SDKVersion  string               `json:"sdkVersion"`
	Files       map[string]SnackFile `json:"files"`
}

// SnackPushResponse is the response from the Snack save API.
type SnackPushResponse struct {
	ID          string `json:"id"`
	HashID      string `json:"hashId"`
	SnackURL    string `json:"snackUrl"`
	PreviewURL  string `json:"previewUrl"`
}

const (
	snackAPIBase   = "https://exp.host/--/api/v2/snack/save"
	snackSDKVersion = "51.0.0"
)

// PushToSnack uploads the React Native project files to Expo Snack and returns a preview URL.
// absProjectDir should be the absolute path to the project workspace directory.
func PushToSnack(absProjectDir, projectName string) (string, error) {
	files, err := collectSnackFiles(absProjectDir)
	if err != nil {
		return "", fmt.Errorf("collecting files: %w", err)
	}
	if len(files) == 0 {
		return "", fmt.Errorf("no source files found in %s", absProjectDir)
	}

	payload := SnackPushRequest{
		Name:        projectName,
		Description: "Generated by Frontend Code Agent",
		SDKVersion:  snackSDKVersion,
		Files:       files,
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshal payload: %w", err)
	}

	client := &http.Client{Timeout: 30 * time.Second}
	req, err := http.NewRequest(http.MethodPost, snackAPIBase, bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Expo-Platform", "web")

	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("POST snack API: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return "", fmt.Errorf("snack API %d: %s", resp.StatusCode, string(respBody))
	}

	var snackResp SnackPushResponse
	if err := json.Unmarshal(respBody, &snackResp); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}

	// Prefer the web preview URL; fall back to the Snack editor URL.
	previewURL := snackResp.PreviewURL
	if previewURL == "" && snackResp.HashID != "" {
		previewURL = fmt.Sprintf("https://snack.expo.dev/%s?platform=web", snackResp.HashID)
	}
	if previewURL == "" && snackResp.ID != "" {
		previewURL = fmt.Sprintf("https://snack.expo.dev/%s?platform=web", snackResp.ID)
	}
	return previewURL, nil
}

// collectSnackFiles walks the project directory and returns a map of Snack-compatible files.
// It skips node_modules, dist, .expo, and binary files.
func collectSnackFiles(root string) (map[string]SnackFile, error) {
	files := make(map[string]SnackFile)

	skipDirs := map[string]bool{
		"node_modules": true,
		"dist":         true,
		".expo":        true,
		".git":         true,
		"android":      true,
		"ios":          true,
	}

	// Text extensions that Snack accepts as CODE type
	textExts := map[string]bool{
		".ts": true, ".tsx": true, ".js": true, ".jsx": true,
		".json": true, ".css": true, ".md": true,
	}

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		rel, _ := filepath.Rel(root, path)
		rel = filepath.ToSlash(rel)

		if info.IsDir() {
			if skipDirs[info.Name()] {
				return filepath.SkipDir
			}
			return nil
		}

		ext := strings.ToLower(filepath.Ext(info.Name()))
		if !textExts[ext] {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return nil
		}

		files[rel] = SnackFile{
			Type:     "CODE",
			Contents: string(content),
		}
		return nil
	})

	return files, err
}
